"""
RSCommendation Backend — FastAPI entry point.

Run locally (outside Docker):
    uvicorn main:app --reload --port 8000

Run via Docker Compose:
    docker compose up
"""

import json
import os
from contextlib import asynccontextmanager
from typing import AsyncGenerator

import numpy as np
from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from src.config import EXCLUDED_ACTIVITY_IDS, WEIGHT_KEYS
from src.firebase import get_app, get_db
from src.ml.nearest_neighbor import build_index
from src.routers import health, recommendations

load_dotenv()

_ARTIFACTS_DIR = os.path.join(os.path.dirname(__file__), "model_artifacts")


# ---------------------------------------------------------------------------
# Lifespan: runs once on startup and once on shutdown
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator[None, None]:
    # --- Startup ---

    # 1. Initialise Firebase / Firestore
    get_app()
    app.state.db = get_db()

    # 2. Stream all activity documents from Firestore.
    docs = list(app.state.db.collection("activities").stream())

    # 3. Filter: must have a weights map and must not be an excluded ID.
    valid_docs = [
        d for d in docs
        if d.to_dict().get("weights") and d.id not in EXCLUDED_ACTIVITY_IDS
    ]

    # 4. Build an in-memory category lookup: doc_id → category slug.
    #    Used at recommendation time to apply the category preference boost
    #    without additional Firestore reads.
    app.state.activity_categories: dict[str, str] = {
        d.id: d.to_dict()["category"]
        for d in valid_docs
        if d.to_dict().get("category")
    }

    # 5. Build the content-based nearest-neighbour index from activity vectors.
    if valid_docs:
        vectors = np.array(
            [
                [d.to_dict()["weights"].get(k, 0.5) for k in WEIGHT_KEYS]
                for d in valid_docs
            ],
            dtype=np.float32,
        )
        item_ids = [d.id for d in valid_docs]
        print(f"[startup] Loaded {len(item_ids)} activities into the NN index.")
    else:
        print("[startup] WARNING: No activities found in Firestore. Index not fitted.")
        vectors = np.empty((0, len(WEIGHT_KEYS)), dtype=np.float32)
        item_ids = []

    app.state.nn_index = build_index(vectors, item_ids)

    # 6. Load historical user profiles for the collaborative recommendation index.
    #    These files are generated by running:  python tools/build_historical_profiles.py
    #    If they do not exist yet, the collaborative endpoint returns 503.
    _load_historical_index(app)

    yield

    # --- Shutdown ---
    # Nothing to clean up for now.


def _load_historical_index(app: FastAPI) -> None:
    """
    Load pre-built historical user profile artifacts and fit a second NN index.

    Expects three files inside model_artifacts/:
        historical_user_vectors.npy      — float32 (n_users, 14)
        historical_user_ids.json         — list[str] in matching row order
        historical_user_activities.json  — {klant_hash: [activity_doc_ids]}

    Sets on app.state:
        historical_nn_index         — NearestNeighborIndex over user profiles
        historical_user_ids         — list[str]
        historical_user_activities  — dict[str, list[str]]
    """
    vectors_path    = os.path.join(_ARTIFACTS_DIR, "historical_user_vectors.npy")
    activities_path = os.path.join(_ARTIFACTS_DIR, "historical_user_activities.json")

    missing = [p for p in (vectors_path, activities_path) if not os.path.exists(p)]
    if missing:
        print(
            f"[startup] Collaborative index NOT loaded — artifact(s) missing: {missing}\n"
            "          Run  python tools/build_historical_profiles.py  to generate them."
        )
        app.state.historical_nn_index = build_index(
            np.empty((0, len(WEIGHT_KEYS)), dtype=np.float32), []
        )
        app.state.historical_user_activities = []
        return

    vectors = np.load(vectors_path)

    with open(activities_path, encoding="utf-8") as f:
        user_activities: list[list[str]] = json.load(f)

    # Use integer row indices as item IDs — no user identifiers are stored.
    row_indices = [str(i) for i in range(len(vectors))]
    app.state.historical_nn_index = build_index(vectors, row_indices)
    app.state.historical_user_activities = user_activities

    print(
        f"[startup] Collaborative index loaded: "
        f"{len(user_activities):,} historical users."
    )


# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(
    title="RSCommendation API",
    description="Radboud Sport & Culture recommendation backend.",
    version="0.1.0",
    lifespan=lifespan,
)

# CORS — allow all origins for development.
# Restrict `allow_origins` to specific domains before going to production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Routers
app.include_router(health.router)
app.include_router(recommendations.router)
