"""
Recommendations router.

GET /recommendations
    Content-based: nearest-neighbour match between the user's onboarding
    preference profile and the activity feature vectors in Firestore.
    - Requires a valid Firebase ID token (Authorization: Bearer <token>)
    - Reads `preferences.features` and `preferences.categories` from Firestore
    - Returns the k nearest activity IDs, re-ranked by category preference

GET /recommendations/collaborative
    Collaborative: find historical RSC members with a similar profile and
    recommend activities those members attended that the user has not tried.
    - Requires a valid Firebase ID token
    - Reads `preferences.features` and `activityRatings` from Firestore
    - Requires model_artifacts/ to be present (run build_historical_profiles.py)
    - Returns a separate list of activity IDs
"""

from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status

from src.config import WEIGHT_KEYS
from src.dependencies import get_current_user
from src.ml.nearest_neighbor import NearestNeighborIndex
from src.models.recommendations import RecommendationResponse
from src.services.collaborative_recommendations import get_collaborative_recommendations
from src.services.recommendations import get_recommendations
from src.services.user_vectors import DEFAULT_VALUE, get_user_full_data

router = APIRouter(prefix="/recommendations", tags=["recommendations"])


@router.get("", response_model=RecommendationResponse)
async def recommendations(
    request: Request,
    k: int = Query(default=10, ge=1, le=50, description="Number of recommendations to return."),
    current_user: dict[str, Any] = Depends(get_current_user),
) -> RecommendationResponse:
    """
    Return the k best-matching activities for the authenticated user.

    Preferences are read from `users/{uid}` in Firestore:
    - `preferences.features`   — 14-dim feature vector for NN lookup
    - `preferences.categories` — 10-dim category preference for re-ranking

    The ML index is built once at startup from the `activities` collection.
    """
    index: NearestNeighborIndex | None = getattr(request.app.state, "nn_index", None)

    if index is None or not index.is_fitted:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Recommendation index is not ready yet.",
        )

    activity_categories: dict[str, str] = getattr(
        request.app.state, "activity_categories", {}
    )

    item_ids = await get_recommendations(
        uid=current_user["uid"],
        k=k,
        db=request.app.state.db,
        nn_index=index,
        activity_categories=activity_categories,
    )

    return RecommendationResponse(item_ids=item_ids)


@router.get("/collaborative", response_model=RecommendationResponse)
async def collaborative_recommendations(
    request: Request,
    k: int = Query(default=10, ge=1, le=50, description="Number of recommendations to return."),
    current_user: dict[str, Any] = Depends(get_current_user),
) -> RecommendationResponse:
    """
    Return up to k activity recommendations via collaborative filtering.

    Finds historical RSC members whose activity-derived profile is closest to
    the authenticated user's onboarding profile, then surfaces activities those
    members attended that the user has not yet tried.

    Requires the model artifacts generated by:
        python tools/build_historical_profiles.py

    Returns HTTP 503 if the historical index has not been loaded.

    Reads from `users/{uid}` in Firestore:
    - `preferences.features`  — 14-dim vector used to find similar historical members
    - `activityRatings`       — activities the user has already tried (excluded from results)
    """
    historical_index: NearestNeighborIndex | None = getattr(
        request.app.state, "historical_nn_index", None
    )

    if historical_index is None or not historical_index.is_fitted:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "Collaborative recommendation index is not available. "
                "Run tools/build_historical_profiles.py and restart the server."
            ),
        )

    uid = current_user["uid"]
    user_data = await get_user_full_data(request.app.state.db, uid)

    # Build the 14-dim feature vector from the user's preference profile
    features_raw = user_data.get("preferences", {}).get("features", {})
    user_vector = [features_raw.get(key, DEFAULT_VALUE) for key in WEIGHT_KEYS]

    # Collect the activity IDs the user has already tried during onboarding
    activity_ratings: dict[str, float] = user_data.get("activityRatings", {})
    tried_activity_ids = set(activity_ratings.keys())

    item_ids = get_collaborative_recommendations(
        user_vector=user_vector,
        tried_activity_ids=tried_activity_ids,
        nn_index=historical_index,
        historical_user_activities=request.app.state.historical_user_activities,
        k=k,
    )

    return RecommendationResponse(item_ids=item_ids)
